services:
  mongo:
    image: mongo:latest
    container_name: "news_summarizer_mongo"
    logging:
      options:
        max-size: 1g
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - local
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: "news_summarizer_qdrant"
    env_file: ".env"
    ports:
      - ${QDRANT_REST_API_PORT}:6333
      - ${QDRANT_GRPC_API_PORT}:6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local
    restart: always

  mysql:
    image: mysql:8.0
    container_name: zenml_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

  zenml:
    image: zenmldocker/zenml-server:0.74.0
    container_name: zenml_server
    ports:
      - "${ZENML_PORT}:8080"
    environment:
      - ZENML_STORE_URL=mysql://root:password@host.docker.internal/zenml
      - ZENML_DEFAULT_USER_NAME=${ZENML_USER}
      - ZENML_DEFAULT_USER_PASSWORD=${ZENML_PASSWORD}
      - ZENML_SERVER_AUTO_ACTIVATE=1
    links:
      - mysql
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    logging:
      options:
        max-size: 1g

volumes:
  mongo_data:
    external: true
  qdrant_data:
    external: true
  mysql_data:

networks:
  local:
    driver: bridge
